/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author surface
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        StatisticForm = new javax.swing.JButton();
        NewBookForm = new javax.swing.JButton();
        NewStudentForm = new javax.swing.JButton();
        NewBookIcon = new javax.swing.JLabel();
        NewStudentIcon = new javax.swing.JLabel();
        StatisticIcon = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        IssueBookForm = new javax.swing.JButton();
        ReturnBookForm = new javax.swing.JButton();
        AboutForm = new javax.swing.JButton();
        AboutIcon = new javax.swing.JLabel();
        ReturnBookIcon = new javax.swing.JLabel();
        IssueBookIcon = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(54, 54, 54));

        jPanel2.setBackground(new java.awt.Color(54, 54, 54));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(54, 54, 54));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 50)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(232, 23, 93));
        jLabel1.setText("WELCOME TO");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 16, -1, 52));

        jLabel3.setBackground(new java.awt.Color(54, 54, 54));
        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 82, 122));
        jLabel3.setText("Library Management System");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 77, 530, -1));

        jPanel1.setBackground(new java.awt.Color(54, 54, 54));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(232, 23, 93)), "OPERATION", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 24), new java.awt.Color(232, 23, 93))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        StatisticForm.setBackground(new java.awt.Color(168, 167, 168));
        StatisticForm.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        StatisticForm.setForeground(new java.awt.Color(204, 82, 122));
        StatisticForm.setText("Statistic");
        StatisticForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StatisticFormActionPerformed(evt);
            }
        });
        jPanel1.add(StatisticForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 160, 128, -1));

        NewBookForm.setBackground(new java.awt.Color(168, 167, 168));
        NewBookForm.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        NewBookForm.setForeground(new java.awt.Color(204, 82, 122));
        NewBookForm.setText("New Book");
        NewBookForm.setBorderPainted(false);
        NewBookForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewBookFormActionPerformed(evt);
            }
        });
        jPanel1.add(NewBookForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 128, -1));

        NewStudentForm.setBackground(new java.awt.Color(168, 167, 168));
        NewStudentForm.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        NewStudentForm.setForeground(new java.awt.Color(204, 82, 122));
        NewStudentForm.setText("New Student");
        NewStudentForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewStudentFormActionPerformed(evt);
            }
        });
        jPanel1.add(NewStudentForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 160, -1, -1));

        NewBookIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/128276131_198361841824973_785138835260618980_n.png"))); // NOI18N
        jPanel1.add(NewBookIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 31, -1, -1));

        NewStudentIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/128382482_411902566794700_2947818827782075943_n.png"))); // NOI18N
        jPanel1.add(NewStudentIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(339, 31, -1, -1));

        StatisticIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/127246972_420232802472382_6607313009987960196_n.png"))); // NOI18N
        jPanel1.add(StatisticIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(659, 31, -1, -1));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 123, 830, 200));

        jPanel4.setBackground(new java.awt.Color(54, 54, 54));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(232, 23, 93)), "ACTION ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 24), new java.awt.Color(232, 23, 93))); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        IssueBookForm.setBackground(new java.awt.Color(168, 167, 168));
        IssueBookForm.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        IssueBookForm.setForeground(new java.awt.Color(204, 82, 122));
        IssueBookForm.setText("Issue Book");
        IssueBookForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IssueBookFormActionPerformed(evt);
            }
        });
        jPanel4.add(IssueBookForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 168, -1, -1));

        ReturnBookForm.setBackground(new java.awt.Color(168, 167, 168));
        ReturnBookForm.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ReturnBookForm.setForeground(new java.awt.Color(204, 82, 122));
        ReturnBookForm.setText("Return Book");
        ReturnBookForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReturnBookFormActionPerformed(evt);
            }
        });
        jPanel4.add(ReturnBookForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(329, 168, -1, -1));

        AboutForm.setBackground(new java.awt.Color(168, 167, 168));
        AboutForm.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        AboutForm.setForeground(new java.awt.Color(204, 82, 122));
        AboutForm.setText("About ");
        AboutForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AboutFormActionPerformed(evt);
            }
        });
        jPanel4.add(AboutForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(641, 168, 128, -1));

        AboutIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/5a3813d34861c6.6832170315136245312965.png"))); // NOI18N
        jPanel4.add(AboutIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(657, 31, -1, -1));

        ReturnBookIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/learning.png"))); // NOI18N
        jPanel4.add(ReturnBookIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, -1, -1));

        IssueBookIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clipart4241261.png"))); // NOI18N
        jPanel4.add(IssueBookIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 336, 830, 210));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/9 Lovely Library Nooks for Your Decorating Inspiration.png"))); // NOI18N
        jLabel9.setText("jLabel9");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, 0, 920, 120));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 864, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jMenuBar1.setBackground(java.awt.SystemColor.activeCaptionText);
        jMenuBar1.setBorder(null);
        jMenuBar1.setAutoscrolls(true);
        jMenuBar1.setBorderPainted(false);
        jMenuBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jMenu1.setForeground(new java.awt.Color(204, 82, 122));
        jMenu1.setText("File");

        jMenuItem1.setForeground(new java.awt.Color(204, 82, 122));
        jMenuItem1.setText("Exit");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setForeground(new java.awt.Color(204, 82, 122));
        jMenuItem2.setText("Logout");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setForeground(new java.awt.Color(204, 82, 122));
        jMenu2.setText("Edit");

        jMenuItem3.setForeground(new java.awt.Color(204, 82, 122));
        jMenuItem3.setText("About");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 4, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        setVisible(false);
        Login log = new Login();
        log.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void NewBookFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewBookFormActionPerformed
    setVisible (false);
        NewBook nb = new NewBook();
        nb.setVisible(true);
    }//GEN-LAST:event_NewBookFormActionPerformed

    private void NewStudentFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewStudentFormActionPerformed
        setVisible (false);
        NewStudent ns = new NewStudent();
        ns.setVisible(true);
    }//GEN-LAST:event_NewStudentFormActionPerformed

    private void ReturnBookFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnBookFormActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        Return  ob = new Return ();
        ob.setVisible(true);
    }//GEN-LAST:event_ReturnBookFormActionPerformed

    private void IssueBookFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IssueBookFormActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        Issue ob = new Issue();
        ob.setVisible(true);
    }//GEN-LAST:event_IssueBookFormActionPerformed

    private void AboutFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AboutFormActionPerformed
        // TODO add your handling code here:
        setVisible (false);
        About ab = new About();
        ab.setVisible(true);
    }//GEN-LAST:event_AboutFormActionPerformed

    private void StatisticFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StatisticFormActionPerformed
            // TODO add your handling code here:
            setVisible (false);
            Statistic ob = new Statistic();
            ob.setVisible(true);
    }//GEN-LAST:event_StatisticFormActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        About ob = new About();
        ob.setVisible(true);   
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AboutForm;
    private javax.swing.JLabel AboutIcon;
    private javax.swing.JButton IssueBookForm;
    private javax.swing.JLabel IssueBookIcon;
    private javax.swing.JButton NewBookForm;
    private javax.swing.JLabel NewBookIcon;
    private javax.swing.JButton NewStudentForm;
    private javax.swing.JLabel NewStudentIcon;
    private javax.swing.JButton ReturnBookForm;
    private javax.swing.JLabel ReturnBookIcon;
    private javax.swing.JButton StatisticForm;
    private javax.swing.JLabel StatisticIcon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
