
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author surface
 */
public class Issue extends javax.swing.JFrame {
    Connection conn;
    ResultSet rs;
    PreparedStatement pst;
    /**
     * Creates new form Issue
     */
    public Issue() {
        super ("Issue Book");
        initComponents();
        conn = javaconnect.ConnecrDb();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BookDetail = new javax.swing.JPanel();
        BookID = new javax.swing.JLabel();
        BookName = new javax.swing.JLabel();
        Genre = new javax.swing.JLabel();
        Edition = new javax.swing.JLabel();
        Price = new javax.swing.JLabel();
        BookIDField = new javax.swing.JTextField();
        BookNameField = new javax.swing.JTextField();
        GenreField = new javax.swing.JTextField();
        EditionField = new javax.swing.JTextField();
        PriceField = new javax.swing.JTextField();
        SearchBookButton = new javax.swing.JButton();
        StudentDetail = new javax.swing.JPanel();
        StudentID = new javax.swing.JLabel();
        Name = new javax.swing.JLabel();
        Surname = new javax.swing.JLabel();
        Major = new javax.swing.JLabel();
        Year = new javax.swing.JLabel();
        StudentIDField = new javax.swing.JTextField();
        NameField = new javax.swing.JTextField();
        SurnameField = new javax.swing.JTextField();
        MajorField = new javax.swing.JTextField();
        YearField = new javax.swing.JTextField();
        SearchStudentButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        DateOfIssue = new javax.swing.JLabel();
        IssueButton = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();
        FindDateIssue = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(54, 54, 54));

        BookDetail.setBackground(new java.awt.Color(54, 54, 54));
        BookDetail.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(232, 23, 93)), "BOOK DETAIL ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 48), new java.awt.Color(232, 23, 93))); // NOI18N
        BookDetail.setForeground(new java.awt.Color(204, 82, 122));

        BookID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BookID.setForeground(new java.awt.Color(204, 82, 122));
        BookID.setText("Book ID");

        BookName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BookName.setForeground(new java.awt.Color(204, 82, 122));
        BookName.setText("Book Name ");

        Genre.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Genre.setForeground(new java.awt.Color(204, 82, 122));
        Genre.setText("Genre ");

        Edition.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Edition.setForeground(new java.awt.Color(204, 82, 122));
        Edition.setText("Edition ");

        Price.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Price.setForeground(new java.awt.Color(204, 82, 122));
        Price.setText("Price ");

        BookIDField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookIDFieldActionPerformed(evt);
            }
        });

        SearchBookButton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        SearchBookButton.setForeground(new java.awt.Color(204, 82, 122));
        SearchBookButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Search.png"))); // NOI18N
        SearchBookButton.setText("Search ");
        SearchBookButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBookButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BookDetailLayout = new javax.swing.GroupLayout(BookDetail);
        BookDetail.setLayout(BookDetailLayout);
        BookDetailLayout.setHorizontalGroup(
            BookDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BookDetailLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BookDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BookID)
                    .addComponent(BookName)
                    .addComponent(Genre)
                    .addComponent(Edition)
                    .addComponent(Price))
                .addGap(24, 24, 24)
                .addGroup(BookDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BookDetailLayout.createSequentialGroup()
                        .addGroup(BookDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BookNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BookIDField, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(GenreField, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EditionField, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addComponent(SearchBookButton))
                    .addComponent(PriceField, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        BookDetailLayout.setVerticalGroup(
            BookDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BookDetailLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(BookDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BookID)
                    .addComponent(BookIDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchBookButton))
                .addGap(24, 24, 24)
                .addGroup(BookDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BookName)
                    .addComponent(BookNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(BookDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Genre)
                    .addComponent(GenreField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(BookDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Edition)
                    .addComponent(EditionField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(BookDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Price)
                    .addComponent(PriceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(159, Short.MAX_VALUE))
        );

        StudentDetail.setBackground(new java.awt.Color(54, 54, 54));
        StudentDetail.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(232, 23, 93)), "STUDENT DETAIL ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 48), new java.awt.Color(232, 23, 93))); // NOI18N

        StudentID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        StudentID.setForeground(new java.awt.Color(204, 82, 122));
        StudentID.setText("Student ID");

        Name.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Name.setForeground(new java.awt.Color(204, 82, 122));
        Name.setText("Name ");

        Surname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Surname.setForeground(new java.awt.Color(204, 82, 122));
        Surname.setText("Surname ");

        Major.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Major.setForeground(new java.awt.Color(204, 82, 122));
        Major.setText("Major ");

        Year.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Year.setForeground(new java.awt.Color(204, 82, 122));
        Year.setText("Year ");

        SearchStudentButton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        SearchStudentButton.setForeground(new java.awt.Color(204, 82, 122));
        SearchStudentButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Search.png"))); // NOI18N
        SearchStudentButton.setText("Search ");
        SearchStudentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchStudentButtonActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(54, 54, 54));

        DateOfIssue.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        DateOfIssue.setForeground(new java.awt.Color(204, 82, 122));
        DateOfIssue.setText("Date of Issue");

        IssueButton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        IssueButton.setForeground(new java.awt.Color(204, 82, 122));
        IssueButton.setText("Issue ");
        IssueButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IssueButtonActionPerformed(evt);
            }
        });

        BackButton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        BackButton.setForeground(new java.awt.Color(204, 82, 122));
        BackButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/back.png"))); // NOI18N
        BackButton.setText("Back ");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(IssueButton)
                    .addComponent(DateOfIssue))
                .addGap(57, 57, 57)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BackButton)
                    .addComponent(FindDateIssue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(DateOfIssue)
                    .addComponent(FindDateIssue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IssueButton)
                    .addComponent(BackButton)))
        );

        javax.swing.GroupLayout StudentDetailLayout = new javax.swing.GroupLayout(StudentDetail);
        StudentDetail.setLayout(StudentDetailLayout);
        StudentDetailLayout.setHorizontalGroup(
            StudentDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StudentDetailLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(StudentDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(StudentDetailLayout.createSequentialGroup()
                        .addGroup(StudentDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(StudentDetailLayout.createSequentialGroup()
                                .addComponent(Major)
                                .addGap(80, 80, 80)
                                .addComponent(MajorField))
                            .addGroup(StudentDetailLayout.createSequentialGroup()
                                .addComponent(Surname)
                                .addGap(55, 55, 55)
                                .addComponent(SurnameField, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(StudentDetailLayout.createSequentialGroup()
                                .addComponent(Year)
                                .addGap(90, 90, 90)
                                .addComponent(YearField))
                            .addGroup(StudentDetailLayout.createSequentialGroup()
                                .addComponent(StudentID)
                                .addGap(44, 44, 44)
                                .addComponent(StudentIDField, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(StudentDetailLayout.createSequentialGroup()
                                .addComponent(Name)
                                .addGap(79, 79, 79)
                                .addComponent(NameField, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(49, 49, 49)
                        .addComponent(SearchStudentButton)
                        .addGap(0, 8, Short.MAX_VALUE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        StudentDetailLayout.setVerticalGroup(
            StudentDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StudentDetailLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(StudentDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StudentID)
                    .addComponent(StudentIDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchStudentButton))
                .addGap(34, 34, 34)
                .addGroup(StudentDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Name)
                    .addComponent(NameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(StudentDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Surname)
                    .addComponent(SurnameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(StudentDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Major)
                    .addComponent(MajorField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(StudentDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Year)
                    .addComponent(YearField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BookDetail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(StudentDetail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BookDetail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(StudentDetail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SearchBookButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBookButtonActionPerformed
        // TODO add your handling code here:
        String sql = "select * from NBook where Book_ID=?";
        try{
            pst=conn.prepareStatement(sql);
            pst.setString(1,BookIDField.getText());
            rs=pst.executeQuery();
            if(rs.next()){
                String add1 = rs.getString("Book_Name");
                BookNameField.setText(add1);
                String add2 = rs.getString("Edition");
                EditionField.setText(add2);
                String add3 = rs.getString("Genre");
                GenreField.setText(add3);
                String add4 = rs.getString("Price");
                PriceField.setText(add4);
                rs.close();
                pst.close();
            }    
                else{
                        JOptionPane.showMessageDialog(null, "Book ID is not found!");
                        }
            
        }catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(null, e);
            } finally{
            try {
                rs.close();
                pst.close();
            }catch(SQLException e){
                
            }
        }
    }//GEN-LAST:event_SearchBookButtonActionPerformed

    private void BookIDFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookIDFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BookIDFieldActionPerformed

    private void SearchStudentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchStudentButtonActionPerformed
        // TODO add your handling code here:
        String sql = "select * from NStudent where Student_ID=?";
        try {
            pst=conn.prepareStatement(sql);
            pst.setString(1, StudentIDField.getText());
            rs=pst.executeQuery();
            if(rs.next()){
                String add6 = rs.getString("Name");
                NameField.setText(add6);
                String add7 = rs.getString("Surname");
                SurnameField.setText(add7);
                String add8 = rs.getString("Major");
                MajorField.setText(add8);
                String add9 = rs.getString("Year");
                YearField.setText(add9);
                rs.close();
                pst.close();           
            }
            else{
                        JOptionPane.showMessageDialog(null, "Student ID is not found!");
                        }
        }catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }finally{
            try {
                rs.close();
                pst.close();
            }catch(SQLException e){
                
            }
        }
    }//GEN-LAST:event_SearchStudentButtonActionPerformed

    public void Delete(){
        String sql ="delete from NBook where Book_ID=?";
        try {
            pst=conn.prepareStatement(sql);
            pst.setString(1, BookIDField.getText());
            pst.execute();
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    public void IssueUpdate(){
        String sql ="Insert into Issue(Book_ID, Book_Name, Genre, Edition, Price, Student_ID, Name, Surname, Major, Year, DateOfIssue) values (?,?,?,?,?,?,?,?,?,?,?)";
        try {
            pst=conn.prepareCall(sql);
            pst.setString(1, BookIDField.getText());
            pst.setString(2, BookNameField.getText());
            pst.setString(3, GenreField.getText());
            pst.setString(4, EditionField.getText());
            pst.setString(5, PriceField.getText());
            pst.setString(6, StudentIDField.getText());
            pst.setString(7, NameField.getText());
            pst.setString(8, SurnameField.getText());
            pst.setString(9, MajorField.getText());
            pst.setString(10, YearField.getText());
            pst.setString(11,((JTextField)FindDateIssue.getDateEditor().getUiComponent()).getText());
            pst.execute();
            JOptionPane.showMessageDialog(null, "Book Issued");
        }catch (HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    private void IssueButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IssueButtonActionPerformed
        // TODO add your handling code here:
        IssueUpdate();
        Delete();
    }//GEN-LAST:event_IssueButtonActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        Home ob = new Home();
        ob.setVisible(true);
    }//GEN-LAST:event_BackButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Issue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Issue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Issue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Issue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Issue().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JPanel BookDetail;
    private javax.swing.JLabel BookID;
    private javax.swing.JTextField BookIDField;
    private javax.swing.JLabel BookName;
    private javax.swing.JTextField BookNameField;
    private javax.swing.JLabel DateOfIssue;
    private javax.swing.JLabel Edition;
    private javax.swing.JTextField EditionField;
    private com.toedter.calendar.JDateChooser FindDateIssue;
    private javax.swing.JLabel Genre;
    private javax.swing.JTextField GenreField;
    private javax.swing.JButton IssueButton;
    private javax.swing.JLabel Major;
    private javax.swing.JTextField MajorField;
    private javax.swing.JLabel Name;
    private javax.swing.JTextField NameField;
    private javax.swing.JLabel Price;
    private javax.swing.JTextField PriceField;
    private javax.swing.JButton SearchBookButton;
    private javax.swing.JButton SearchStudentButton;
    private javax.swing.JPanel StudentDetail;
    private javax.swing.JLabel StudentID;
    private javax.swing.JTextField StudentIDField;
    private javax.swing.JLabel Surname;
    private javax.swing.JTextField SurnameField;
    private javax.swing.JLabel Year;
    private javax.swing.JTextField YearField;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
