import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Random;
import javax.swing.JOptionPane;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author surface
 */
public class NewStudent extends javax.swing.JFrame {
    Connection conn;
    ResultSet rs;
    PreparedStatement pst;
    /**
     * Creates new form NewStudent
     */
    public NewStudent() {
       super ("New Book");
       initComponents();
       conn = javaconnect.ConnecrDb();
       Random();
    }
    public void Random(){
        Random rd = new Random();
        StudentIDField.setText("" + rd.nextInt(2000+1));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AddStudentPanel = new javax.swing.JPanel();
        Name = new javax.swing.JLabel();
        SurnameField = new javax.swing.JTextField();
        StudentID = new javax.swing.JLabel();
        StudentIDField = new javax.swing.JTextField();
        Major = new javax.swing.JLabel();
        Surname = new javax.swing.JLabel();
        Year = new javax.swing.JLabel();
        NameField = new javax.swing.JTextField();
        ChooseMajor = new javax.swing.JComboBox<>();
        ChooseYear = new javax.swing.JComboBox<>();
        AddStudentButton = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        AddStudentPanel.setBackground(new java.awt.Color(54, 54, 54));
        AddStudentPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(232, 23, 93)), "ADD NEW STUDENT", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 36), new java.awt.Color(232, 23, 93))); // NOI18N

        Name.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Name.setForeground(new java.awt.Color(204, 82, 122));
        Name.setText("Name");

        StudentID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        StudentID.setForeground(new java.awt.Color(204, 82, 122));
        StudentID.setText("Student ID");

        Major.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Major.setForeground(new java.awt.Color(204, 82, 122));
        Major.setText("Major");

        Surname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Surname.setForeground(new java.awt.Color(204, 82, 122));
        Surname.setText("Surname");

        Year.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Year.setForeground(new java.awt.Color(204, 82, 122));
        Year.setText("Year");

        ChooseMajor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Business Administration", "Computer Science and Engineering", "Electrical Engineering", "Biotechnology", "Mathematic", "Physics", "Biomedical Engineering", "Civil Engineering", "Industrial and Systems Engineering", "English", "Environmental Engineering" }));

        ChooseYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "K16", "K17", "K18", "K19", "K20", " " }));

        AddStudentButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        AddStudentButton.setForeground(new java.awt.Color(232, 23, 93));
        AddStudentButton.setText("Add");
        AddStudentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddStudentButtonActionPerformed(evt);
            }
        });

        BackButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BackButton.setForeground(new java.awt.Color(232, 23, 93));
        BackButton.setText("Back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AddStudentPanelLayout = new javax.swing.GroupLayout(AddStudentPanel);
        AddStudentPanel.setLayout(AddStudentPanelLayout);
        AddStudentPanelLayout.setHorizontalGroup(
            AddStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddStudentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AddStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Name)
                    .addComponent(StudentID)
                    .addComponent(Surname)
                    .addComponent(Major)
                    .addComponent(Year))
                .addGap(60, 60, 60)
                .addGroup(AddStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddStudentPanelLayout.createSequentialGroup()
                        .addComponent(AddStudentButton)
                        .addGap(50, 50, 50)
                        .addComponent(BackButton))
                    .addGroup(AddStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(StudentIDField)
                        .addComponent(NameField)
                        .addComponent(SurnameField)
                        .addComponent(ChooseMajor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ChooseYear, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        AddStudentPanelLayout.setVerticalGroup(
            AddStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddStudentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AddStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(AddStudentPanelLayout.createSequentialGroup()
                        .addGroup(AddStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(StudentID)
                            .addComponent(StudentIDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(55, 55, 55)
                        .addGroup(AddStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Name)
                            .addComponent(NameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(59, 59, 59)
                        .addGroup(AddStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Surname)
                            .addComponent(SurnameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(62, 62, 62)
                        .addComponent(Major))
                    .addComponent(ChooseMajor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(AddStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ChooseYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Year))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(AddStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddStudentButton)
                    .addComponent(BackButton))
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AddStudentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AddStudentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        // TODO add your handling code here:
        setVisible (false);
        Home ha = new Home();
        ha.setVisible(true);
    }//GEN-LAST:event_BackButtonActionPerformed

    private void AddStudentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddStudentButtonActionPerformed
        // TODO add your handling code here:
        String sql = "insert into NStudent (Student_ID,Name,Surname,Major,Year) values (?,?,?,?,?)";
        try{
            pst = conn.prepareStatement(sql);
            pst.setString(1, StudentIDField.getText());
            pst.setString(2, NameField.getText());
            pst.setString(3, SurnameField.getText());
            pst.setString(4, (String) ChooseMajor.getSelectedItem());
            pst.setString(5, (String) ChooseYear.getSelectedItem());
            pst.execute();
            JOptionPane.showMessageDialog(null, "New Student Added");
        }catch (Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_AddStudentButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewStudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddStudentButton;
    private javax.swing.JPanel AddStudentPanel;
    private javax.swing.JButton BackButton;
    private javax.swing.JComboBox<String> ChooseMajor;
    private javax.swing.JComboBox<String> ChooseYear;
    private javax.swing.JLabel Major;
    private javax.swing.JLabel Name;
    private javax.swing.JTextField NameField;
    private javax.swing.JLabel StudentID;
    private javax.swing.JTextField StudentIDField;
    private javax.swing.JLabel Surname;
    private javax.swing.JTextField SurnameField;
    private javax.swing.JLabel Year;
    // End of variables declaration//GEN-END:variables
}
