
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author surface
 */
public class Return extends javax.swing.JFrame {
    Connection conn;
    ResultSet rs;
    PreparedStatement pst;
    /**
     * Creates new form Return
     */
    public Return() {
        super ("Return Book");
        initComponents();
        conn = javaconnect.ConnecrDb();
    }
    
    public void Delete(){
        String sql ="delete from Issue where Student_ID=?";
        try {
             pst=conn.prepareStatement(sql);
            pst.setString(1, StudentIDField.getText());
            pst.execute();
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }

    public void ReturnUpdate(){
        String sql ="insert into ReturnB(Student_ID, Name, Surname, Major, Year, Book_ID, Book_Name, Genre, Edition, Price, DateOfIssue, DateOfReturn) values (?,?,?,?,?,?,?,?,?,?,?,?)";
        try{
        pst=conn.prepareStatement(sql);
        pst.setString(1, StudentIDField.getText());
        pst.setString(2, NameField.getText());
        pst.setString(3, SurnameField.getText());
        pst.setString(4, MajorField.getText());
        pst.setString(5, YearField.getText());
        pst.setString(6, BookIDField.getText());
        pst.setString(7, BookNameField.getText());
        pst.setString(8, GenreField.getText());
        pst.setString(9, EditionField.getText());
        pst.setString(10, PriceField.getText());
        pst.setString(11, DateOfIssueField.getText());
        pst.setString(12, ((JTextField) ChooseDateReturn.getDateEditor().getUiComponent()).getText());
        pst.execute();
        JOptionPane.showMessageDialog(null,"Book Returned");
    
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    public void Update(){
        String sql ="insert into NBook(Book_ID, Book_Name, Genre, Edition, Price) values (?,?,?,?,?)";
        try{
        pst=conn.prepareStatement(sql);
        pst.setString(1, BookIDField.getText());
        pst.setString(2, BookNameField.getText());
        pst.setString(3, GenreField.getText());
        pst.setString(4, EditionField.getText());
        pst.setString(5, PriceField.getText());
        pst.execute();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        ReturnPanel = new javax.swing.JPanel();
        StudentID = new javax.swing.JLabel();
        Name = new javax.swing.JLabel();
        Surname = new javax.swing.JLabel();
        Major = new javax.swing.JLabel();
        Year = new javax.swing.JLabel();
        StudentIDField = new javax.swing.JTextField();
        NameField = new javax.swing.JTextField();
        SurnameField = new javax.swing.JTextField();
        MajorField = new javax.swing.JTextField();
        YearField = new javax.swing.JTextField();
        BookID = new javax.swing.JLabel();
        BookName = new javax.swing.JLabel();
        Genre = new javax.swing.JLabel();
        Edition = new javax.swing.JLabel();
        Price = new javax.swing.JLabel();
        BookIDField = new javax.swing.JTextField();
        BookNameField = new javax.swing.JTextField();
        GenreField = new javax.swing.JTextField();
        EditionField = new javax.swing.JTextField();
        PriceField = new javax.swing.JTextField();
        ReturnDate = new javax.swing.JLabel();
        DateOfIssue = new javax.swing.JLabel();
        ReturnButton = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();
        SearchStudentButton = new javax.swing.JButton();
        ChooseDateReturn = new com.toedter.calendar.JDateChooser();
        DateOfIssueField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ReturnPanel.setBackground(new java.awt.Color(54, 54, 54));
        ReturnPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(232, 23, 93)), "RETURN PANEL ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 36), new java.awt.Color(232, 23, 93))); // NOI18N

        StudentID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        StudentID.setForeground(new java.awt.Color(204, 82, 122));
        StudentID.setText("Student ID");

        Name.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Name.setForeground(new java.awt.Color(204, 82, 122));
        Name.setText("Name ");

        Surname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Surname.setForeground(new java.awt.Color(204, 82, 122));
        Surname.setText("Surname ");

        Major.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Major.setForeground(new java.awt.Color(204, 82, 122));
        Major.setText("Major ");

        Year.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Year.setForeground(new java.awt.Color(204, 82, 122));
        Year.setText("Year ");

        BookID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BookID.setForeground(new java.awt.Color(204, 82, 122));
        BookID.setText("Book ID");

        BookName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BookName.setForeground(new java.awt.Color(204, 82, 122));
        BookName.setText("Book Name ");

        Genre.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Genre.setForeground(new java.awt.Color(204, 82, 122));
        Genre.setText("Genre ");

        Edition.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Edition.setForeground(new java.awt.Color(204, 82, 122));
        Edition.setText("Edition ");

        Price.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Price.setForeground(new java.awt.Color(204, 82, 122));
        Price.setText("Price ");

        ReturnDate.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        ReturnDate.setForeground(new java.awt.Color(204, 82, 122));
        ReturnDate.setText("Date of Issue ");

        DateOfIssue.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        DateOfIssue.setForeground(new java.awt.Color(204, 82, 122));
        DateOfIssue.setText("Return Date:");

        ReturnButton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        ReturnButton.setForeground(new java.awt.Color(204, 82, 122));
        ReturnButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Search.png"))); // NOI18N
        ReturnButton.setText("Return ");
        ReturnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReturnButtonActionPerformed(evt);
            }
        });

        BackButton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        BackButton.setForeground(new java.awt.Color(204, 82, 122));
        BackButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/back.png"))); // NOI18N
        BackButton.setText("Back ");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        SearchStudentButton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        SearchStudentButton.setForeground(new java.awt.Color(204, 82, 122));
        SearchStudentButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Search.png"))); // NOI18N
        SearchStudentButton.setText("Search");
        SearchStudentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchStudentButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ReturnPanelLayout = new javax.swing.GroupLayout(ReturnPanel);
        ReturnPanel.setLayout(ReturnPanelLayout);
        ReturnPanelLayout.setHorizontalGroup(
            ReturnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ReturnPanelLayout.createSequentialGroup()
                .addGroup(ReturnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ReturnPanelLayout.createSequentialGroup()
                        .addContainerGap(18, Short.MAX_VALUE)
                        .addGroup(ReturnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(StudentID)
                            .addComponent(Name)
                            .addComponent(Surname)
                            .addComponent(Major)
                            .addComponent(Year))
                        .addGap(47, 47, 47)
                        .addGroup(ReturnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(StudentIDField)
                            .addComponent(NameField)
                            .addComponent(SurnameField)
                            .addComponent(MajorField)
                            .addComponent(YearField, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(SearchStudentButton)
                        .addGap(42, 42, 42)
                        .addGroup(ReturnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BookID)
                            .addComponent(BookName)
                            .addComponent(Genre)
                            .addComponent(Edition)
                            .addComponent(Price)
                            .addComponent(ReturnDate)
                            .addComponent(DateOfIssue))
                        .addGroup(ReturnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ReturnPanelLayout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(ChooseDateReturn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ReturnPanelLayout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addGroup(ReturnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(DateOfIssueField)
                                    .addComponent(BookIDField, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                                    .addComponent(BookNameField)
                                    .addComponent(GenreField)
                                    .addComponent(EditionField)
                                    .addComponent(PriceField)))))
                    .addGroup(ReturnPanelLayout.createSequentialGroup()
                        .addGap(523, 523, 523)
                        .addComponent(ReturnButton)
                        .addGap(62, 62, 62)
                        .addComponent(BackButton)))
                .addGap(46, 46, 46))
        );
        ReturnPanelLayout.setVerticalGroup(
            ReturnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ReturnPanelLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(ReturnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StudentID)
                    .addComponent(StudentIDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BookID)
                    .addComponent(BookIDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchStudentButton))
                .addGap(34, 34, 34)
                .addGroup(ReturnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Name)
                    .addComponent(NameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BookName)
                    .addComponent(BookNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(ReturnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Surname)
                    .addComponent(SurnameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Genre)
                    .addComponent(GenreField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(ReturnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Major)
                    .addComponent(MajorField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Edition)
                    .addComponent(EditionField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(ReturnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Year)
                    .addComponent(YearField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Price)
                    .addComponent(PriceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(ReturnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ReturnDate)
                    .addComponent(DateOfIssueField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(ReturnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(DateOfIssue)
                    .addComponent(ChooseDateReturn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(ReturnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ReturnButton)
                    .addComponent(BackButton))
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(ReturnPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(ReturnPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SearchStudentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchStudentButtonActionPerformed
        // TODO add your handling code here:
        String sql ="select * from Issue where Student_ID=?";
        try {
            pst=conn.prepareStatement(sql);
            pst.setString(1, StudentIDField.getText());
            rs=pst.executeQuery();
            if(rs.next()){
                String add1 = rs.getString("Name");
                NameField.setText(add1);
                String add2 = rs.getString("Surname");
                SurnameField.setText(add2);
                String add3 = rs.getString("Major");
                MajorField.setText(add3);
                String add4 = rs.getString("Year");
                YearField.setText(add4);
                String add5 = rs.getString("Book_ID");
                BookIDField.setText(add5);
                String add6 = rs.getString("Book_Name");
                BookNameField.setText(add6);
                String add8 = rs.getString("Genre");
                GenreField.setText(add8);
                String add9 = rs.getString("Edition");
                EditionField.setText(add9);
                String add10 = rs.getString("Price");
                PriceField.setText(add10);
                String add11 = rs.getString("DateofIssue");
                DateOfIssueField.setText(add11);
                rs.close();
                pst.close();           
            }
            else{
                JOptionPane.showMessageDialog(null, "Book is not issued with this Student ID!");
                }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }finally{
            try{
                rs.close();
                pst.close(); 
            }catch (Exception e){
                
            }
        }
    }//GEN-LAST:event_SearchStudentButtonActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        Home ob=new Home();
        ob.setVisible(true);
    }//GEN-LAST:event_BackButtonActionPerformed

    private void ReturnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnButtonActionPerformed
        // TODO add your handling code here:
        Delete();
        ReturnUpdate();
        Update();  
    }//GEN-LAST:event_ReturnButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Return.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Return.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Return.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Return.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Return().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JLabel BookID;
    private javax.swing.JTextField BookIDField;
    private javax.swing.JLabel BookName;
    private javax.swing.JTextField BookNameField;
    private com.toedter.calendar.JDateChooser ChooseDateReturn;
    private javax.swing.JLabel DateOfIssue;
    private javax.swing.JTextField DateOfIssueField;
    private javax.swing.JLabel Edition;
    private javax.swing.JTextField EditionField;
    private javax.swing.JLabel Genre;
    private javax.swing.JTextField GenreField;
    private javax.swing.JLabel Major;
    private javax.swing.JTextField MajorField;
    private javax.swing.JLabel Name;
    private javax.swing.JTextField NameField;
    private javax.swing.JLabel Price;
    private javax.swing.JTextField PriceField;
    private javax.swing.JButton ReturnButton;
    private javax.swing.JLabel ReturnDate;
    private javax.swing.JPanel ReturnPanel;
    private javax.swing.JButton SearchStudentButton;
    private javax.swing.JLabel StudentID;
    private javax.swing.JTextField StudentIDField;
    private javax.swing.JLabel Surname;
    private javax.swing.JTextField SurnameField;
    private javax.swing.JLabel Year;
    private javax.swing.JTextField YearField;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables

    private static class jTextField11 {

        private static void setText(String add10) {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }

        private static String getText() {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }

        public jTextField11() {
        }
    }

    private static class jTextField12 {

        private static void setText(String add11) {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }

        public jTextField12() {
        }
    }
}
